name: CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go:
    name: Go
    runs-on: ubuntu-latest

    env:
      GOPRIVATE: github.com/tyler180/*

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -race ./...

      - name: Build
        run: go build ./...